db:
  image: dgraziotin/mysql
  ports:
    - "3306:3306"
  volumes:
    - ./db:/var/lib/mysql
  environment:
    - MYSQL_ADMIN_PASS=triptyk
web:
  image: triptyk/apache
  ports:
    - "80:80"
  volumes:
    - ./environment/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    - ./www:/var/www
    - ./logs:/var/log/apache2
  links:
    - db
